### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by 1arsi1** [WzrterFX/cs2-aimbot#1]
add rcs and triggerbot

**Comment by WzrterFX** [comment]
I'll make a full cheat later

**Comment by 1arsi1** [comment]
maybe you could upload every day what you would add so I can understand your code better and maybe help with it in the future.

**Comment by WzrterFX** [comment]
I want to post a full cheat

**Comment by jammesop007aha** [comment]
> I'll make a full cheat later

ok
